### ISSUE TITLE
vr/isearch-forward very slow

### ISSUE THREAD

**Issue by smcallis** [benma/visual-regexp-steroids.el#27] opened 2018-08-15 14:51 UTC
I'm having a problem, I've got vr/isearch-forward bound to C-s, which works fine at home.  But on my work computer it's _very_ slow, there's a noticeable lag from keypress to keypress.  Is there any way to speed that up?  Looking at the code it looks like it spawns a sub-process but I'm not sure exactly how often...

**Comment by benma** [comment] 2018-08-15 15:33
Hi

Check a similar issue here:

https://github.com/benma/visual-regexp.el/issues/52#issuecomment-335147520

Could this be the reason?

**Comment by smcallis** [comment] 2018-08-15 15:40
That's almost certainly the reason, there's a lot more cruft in my work
python.  Is there any way to amortize that process cost?  Maybe keep the
sub-process open and pipe requests in/out?

**Comment by benma** [comment] 2019-04-14 08:44
Yes, something like this would be the solution. I'll close this as a duplicate of https://github.com/benma/visual-regexp.el/issues/52

**Closed as completed by benma** 2019-04-14 08:44 UTC
